# Generated by Django 5.0.7 on 2024-07-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0004_post_short_description_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='cover_image',
        ),
    ]
