# Generated by Django 5.0.7 on 2024-07-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0006_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
